DROP TABLE IF EXISTS Test;

CREATE TABLE Test (
	id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	text VARCHAR(30) NOT NULL
);

START TRANSACTION;
INSERT INTO Test(text) VALUES
	('v1'),
	('v2'),
	('v3'),
	('v4'),
	('v5');
COMMIT;
	
	
SELECT * FROM Test;